### ISSUE TITLE
ngx-leaflet-draw set polygon points during initialization

### ISSUE THREAD

**Issue by Mirosvo92** [Asymmetrik/ngx-leaflet-draw#65] opened 2018-11-14 16:54 UTC
Hello!) I need help with use leaflet-draw. Tell me, please, I use Angular 6, I want to set points on the polygon during component initialization that the user can change.

**Comment by Mirosvo92** [comment] 2018-11-16 08:31
Hello!) I am sorry for my question, I have found answer, thank you for your work)

**Comment by reblace** [comment] 2018-12-14 01:37
Closing cause it sounds like the issue is resolved. Thanks!

**Closed by reblace** 2018-12-14 01:37 UTC

**Comment by Mirosvo92** [comment] 2019-05-14 08:00
> @Mirosvo92
> 
> Can you please link to where you found the solution? Thanks.

I used this settings in component:
`    @Input() pointsCoor: any[];
  map: L.Map;
  lay: L.Layer[] = [];
  editableLayers = new L.FeatureGroup();
  coord: any[];
  //
  drawOptions = {
    position: 'topright',
    draw: false,
    edit: {featureGroup: this.editableLayers, remove: false}
  };

  onMapReady(map: L.Map) {
    ....
  }

  onDrawReady(drawControl: L.Control.Draw) {
    this.map.on(L.Draw.Event.EDITED, (e) => {
      ...
    });
  }

`
in view
`<div id="map" style="width: 100%; height: 400px;"
     leaflet
     leafletDraw
     [leafletOptions]="options"
     [leafletDrawOptions]="drawOptions"
     (leafletMapReady)="onMapReady($event)"
     [leafletLayers]="lay"
     [(leafletCenter)]="center"
     (leafletDrawReady)="onDrawReady($event)">
</div>
`

**Comment by Mirosvo92** [comment] 2019-05-14 08:01
> @Mirosvo92
> 
> Can you please link to where you found the solution? Thanks.

and I have found some example
https://github.com/TheMaximumDrive/dosaX
you can use it

**Comment by NilNadirler** [comment] 2022-10-10 08:25
> onDrawReady(drawControl: L.Control.Draw) {
> this.map.on(L.Draw.Event.EDITED, (e) => {
> ...
> });
> }

Hello, Could you add more detail please? I am in trouble for edit polygon and get the update coordinates

**Comment by NilNadirler** [comment] 2022-10-10 13:28
My question is hot [leafletDrawOptions]="drawOptions" edit L.polygon?
